### ISSUE TITLE
Simply wont work

### ISSUE THREAD

**Issue by DvineDK** [lehjr/MachineMusePowersuits#33]
Every time i want to put a module or a battery or anything in the armor, it simply wont be installed on the armor and drops on the ground. I cannot install High Efficiency Solar generator nor the Kinetic Generator. This new tinker station ui is garbage and not user friendly. I would urge you to be able to press the suit-part that you want to upgrade and simply be able to press "install" if you have the required materials, just like the old version. Also, is Diamond Plating not supposed to give the same armor/more than regular diamond armor? Because it just gives me the armor of Iron

**Comment by ProsperCraft** [comment]
Yes, my son ragequit last night due to this interface and the batteries falling out...items going missing, and eventually his entire helmet disappeared.

The new UI is very hard to understand, almost to the point of being unusable.

When you put items in if you don't click back and for the between the tabs a few times the items you put in fall to the ground, or simply disappear.

The tinker table itself also disappeared when broken with an atomic disassembler from Mek which is a pick.

I had the same issue as my son, relogging did not bring back lost items.

ModularPowersuits-1.16.5-2.1.17
Numina-1.16.5-2.1.14
Dedicated server.

Modpack- TownCraft TWO for 1.16.5

**Comment by ProsperCraft** [comment]
A workaround we have found to this, is to take off all powersuit things, and put them in a chest, then only holding one item in your hand, click on the tinker table with that item in your hand and only upgrade that, make sure it is complete before exiting the table by clicking back and forth a few times on the tabs then exit the table and verify it kept.  Then put that in the chest and do the same with the next part.

**Comment by lehjr** [comment]
> Every time i want to put a module or a battery or anything in the armor, it simply wont be installed on the armor and drops on the ground. I cannot install High Efficiency Solar generator nor the Kinetic Generator. This new tinker station ui is garbage and not user friendly. I would urge you to be able to press the suit-part that you want to upgrade and simply be able to press "install" if you have the required materials, just like the old version. Also, is Diamond Plating not supposed to give the same armor/more than regular diamond armor? Because it just gives me the armor of Iron

The installation has changed because modules have changed due to the changes in the base code in Minecraft as well as changes in Forge. So while the new UI is pretty much garbage, there is no going back. It will likely be rewritten yet again, but when I have the time, and not one moment before. But since the mod is opensource you're more than welcome to try it yourself.

**Comment by lehjr** [comment]
issues with multiplayer/dedicated servers have been fixed. Crafting portion of the GUI has been removed.
